#!/usr/bin/env python3
"""
gen_header.py — ECG 코퍼스를 C 헤더로 변환

BioGPT-S3 가 학습할 수 있도록 텍스트 코퍼스를 C 헤더 파일로 변환합니다.

사용법:
    python tools/gen_header.py corpus/ecg_train.txt src/corpus_ecg.h
    python tools/gen_header.py corpus/ecg_train.txt src/corpus_ecg.h --holdout corpus/ecg_val.txt
"""

import sys
from pathlib import Path

def escape(text: str) -> str:
    out = []
    for ch in text:
        if ch == '\\':
            out.append('\\\\')
        elif ch == '"':
            out.append('\\"')
        elif ch == '\n':
            out.append('\\n')
        elif ch == '\t':
            out.append('\\t')
        else:
            out.append(ch)
    return ''.join(out)

def main():
    if len(sys.argv) < 3:
        print("usage: python gen_header.py input.txt output.h [--holdout val.txt]")
        sys.exit(1)
    
    src_path = Path(sys.argv[1])
    dst_path = Path(sys.argv[2])
    
    holdout_path = None
    if '--holdout' in sys.argv:
        idx = sys.argv.index('--holdout')
        if idx + 1 < len(sys.argv):
            holdout_path = Path(sys.argv[idx + 1])
    
    # 코퍼스 읽기
    raw = src_path.read_text(encoding='utf-8').replace('\r', '')
    
    # Hold-out 세트
    val = None
    if holdout_path and holdout_path.exists():
        val = holdout_path.read_text(encoding='utf-8').replace('\r', '')
    
    # 어휘 체크
    NV = 20  # platformio.ini 와 일치
    vocab = sorted(set((raw + (val or '')).encode('utf-8')))
    
    if len(vocab) > NV:
        print(f"ERROR: corpus uses {len(vocab)} distinct bytes, max is {NV}")
        print("Raise NV in platformio.ini and handgpt_ple.h")
        sys.exit(1)
    
    # C 헤더 생성
    chunk = 2000
    lines = [
        "// Generated by tools/gen_header.py — do not edit",
        "#pragma once",
        f"#define KLIN_CORPUS_LEN {len(raw.encode('utf-8'))}",
        "static const char KLIN_CORPUS[] =",
    ]
    
    for i in range(0, len(raw), chunk):
        lines.append('"%s"' % escape(raw[i:i + chunk]))
    lines.append(';')
    
    # Hold-out 세트 추가
    if val:
        lines += [
            "",
            "// Hold-out set for validation",
            f"#define KLIN_HELDOUT_LEN {len(val.encode('utf-8'))}",
            "static const char KLIN_HELDOUT[] =",
        ]
        for i in range(0, len(val), chunk):
            lines.append('"%s"' % escape(val[i:i + chunk]))
        lines.append(';')
    
    # 파일 쓰기
    dst_path.parent.mkdir(parents=True, exist_ok=True)
    dst_path.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    
    print(f"wrote {dst_path}")
    print(f"  train: {len(raw.encode('utf-8'))} bytes")
    print(f"  vocab: {len(vocab)}/{NV} bytes")
    if val:
        print(f"  holdout: {len(val.encode('utf-8'))} bytes ({100 * len(val.encode('utf-8')) / len((raw + val).encode('utf-8')):.1f}%)")

if __name__ == '__main__':
    main()
